# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PromptDetDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PromptDetDialog(object):
    def setupUi(self, PromptDetDialog):
        PromptDetDialog.setObjectName("PromptDetDialog")
        PromptDetDialog.resize(466, 225)
        self.gridLayout = QtWidgets.QGridLayout(PromptDetDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.IPLabel = QtWidgets.QLabel(PromptDetDialog)
        self.IPLabel.setObjectName("IPLabel")
        self.horizontalLayout.addWidget(self.IPLabel)
        self.IPLineEdit = QtWidgets.QLineEdit(PromptDetDialog)
        self.IPLineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.IPLineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.IPLineEdit.setObjectName("IPLineEdit")
        self.horizontalLayout.addWidget(self.IPLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.portLabel = QtWidgets.QLabel(PromptDetDialog)
        self.portLabel.setObjectName("portLabel")
        self.horizontalLayout.addWidget(self.portLabel)
        self.portSpinBox = QtWidgets.QSpinBox(PromptDetDialog)
        self.portSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.portSpinBox.setMaximum(99999)
        self.portSpinBox.setSingleStep(1)
        self.portSpinBox.setProperty("value", 52007)
        self.portSpinBox.setObjectName("portSpinBox")
        self.horizontalLayout.addWidget(self.portSpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(58, 29, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.thrLabel = QtWidgets.QLabel(PromptDetDialog)
        self.thrLabel.setObjectName("thrLabel")
        self.horizontalLayout.addWidget(self.thrLabel)
        self.thrDoubleSpinBox = QtWidgets.QDoubleSpinBox(PromptDetDialog)
        self.thrDoubleSpinBox.setMinimum(0.0)
        self.thrDoubleSpinBox.setMaximum(1.0)
        self.thrDoubleSpinBox.setSingleStep(0.05)
        self.thrDoubleSpinBox.setProperty("value", 0.3)
        self.thrDoubleSpinBox.setObjectName("thrDoubleSpinBox")
        self.horizontalLayout.addWidget(self.thrDoubleSpinBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.promptLabel = QtWidgets.QLabel(PromptDetDialog)
        self.promptLabel.setObjectName("promptLabel")
        self.verticalLayout.addWidget(self.promptLabel)
        self.promptLineEdit = QtWidgets.QLineEdit(PromptDetDialog)
        self.promptLineEdit.setObjectName("promptLineEdit")
        self.verticalLayout.addWidget(self.promptLineEdit)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.classLabel = QtWidgets.QLabel(PromptDetDialog)
        self.classLabel.setObjectName("classLabel")
        self.verticalLayout_2.addWidget(self.classLabel)
        self.classLineEdit = QtWidgets.QLineEdit(PromptDetDialog)
        self.classLineEdit.setObjectName("classLineEdit")
        self.verticalLayout_2.addWidget(self.classLineEdit)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(PromptDetDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 1)

        self.retranslateUi(PromptDetDialog)
        self.buttonBox.accepted.connect(PromptDetDialog.accept)
        self.buttonBox.rejected.connect(PromptDetDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PromptDetDialog)

    def retranslateUi(self, PromptDetDialog):
        _translate = QtCore.QCoreApplication.translate
        PromptDetDialog.setWindowTitle(_translate("PromptDetDialog", "万能检测"))
        self.IPLabel.setText(_translate("PromptDetDialog", "IP:"))
        self.IPLineEdit.setInputMask(_translate("PromptDetDialog", "000.000.000.000"))
        self.IPLineEdit.setText(_translate("PromptDetDialog", "192.168.0.63"))
        self.portLabel.setText(_translate("PromptDetDialog", "端口:"))
        self.thrLabel.setText(_translate("PromptDetDialog", "默认阈值:"))
        self.promptLabel.setText(_translate("PromptDetDialog", "提示词:(仅支持英文,=之后是该词的阈值,使用;分隔)"))
        self.promptLineEdit.setText(_translate("PromptDetDialog", "people=0.3;helmet;dryer"))
        self.classLabel.setText(_translate("PromptDetDialog", "类别名:(为空即使用提示词作为标签,=之后是提示词标签,使用;分隔)"))
        self.classLineEdit.setText(_translate("PromptDetDialog", "helmet=aqmzc;dryer=hxq"))
